// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wosnmsdvgpmdtuipgkot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indvc25tc2R2Z3BtZHR1aXBna290Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDEwMjEsImV4cCI6MjA3MTM3NzAyMX0.Bakt7b37RuJBC6PziLlOvh2IZMpis5C3uVw1MbGv6RA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});